# Site settings
title: Reigning Phoenix
email: ReigningPhoenixEquestrian@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/index/" # the subpath of your site, e.g. /blog/
url: "https://reigningphoenix.github.io/" # the base hostname & protocol for your site

github_username: ReigningPhoenix

# Build settings
markdown: kramdown
