# Site settings
title: My Page
email: omrfrkyildiz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The theme includes a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://omrfyildiz.github.io/creative-theme-jekyll/" # the base hostname & protocol for your site

twitter_username: omrfyildiz
github_username:  omrfyildiz

# Build settings
markdown: kramdown
