# Site settings
title:
email: ariss.n.sabrina@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "portolio" # the subpath of your site, e.g. /blog/
url: "sabrina" # the base hostname & protocol for your site

twitter_username:
github_username: sabrinaariss

# Build settings
markdown: kramdown
