# Site settings
title: LatamBusinessClub
email: latambusinessclubnu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: LatamNU

# Build settings
markdown: kramdown
