# Site settings
title: Carlos Alexandre Costa 
email: c.alexandre241@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The theme includes a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://carl1988a.github.io/" # the base hostname & protocol for your site

twitter_username: @Carlos_Ale_88
github_username:  Carl1988A

# Build settings
markdown: kramdown
