# Site settings
title: Nischay Bikram Thapa
email: nischaybikramthapa14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

instagram_username: _nischay.t
github_username: nischaybikramthapa

# Build settings
markdown: kramdown
