# Site settings
title: Portfolio personal
email: gpozzi@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: gpozzi__
github_username:  gpozzi

# Build settings
markdown: kramdown
future: true
timezone: America/Argentina/Buenos_Aires
