# Site settings
title: Le Penon Surf House
email: delord.kevin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "lepenon-surfhouse.fr" # the base hostname & protocol for your site

twitter_username: DKLogs
github_username: kevindelord

# Build settings
markdown: kramdown

sass:
  compressed: true

include: ['_activities', '_services', '_languages']
exclude: ['reboot.sh', 'README.md', 'LICENSE']

collections:
  activities:
    output: false
  services:
    output: false
  languages:
    output: false

permalink: pretty

#
# Translations

t:
  nav:
    gallery:
      en: "Gallery"
      fr: "Gallerie"
    services:
      en: "Amenities"
      fr: "Aménagement"
    activities:
      en: "Activities"
      fr: "Activités"
    contact:
      en: "Contact"
      fr: "Contact"